import type { BusinessExtractionProposal, DealRoomState } from "./types";

// Fictional, session-local material. No customer conversation is imported here.
const proposals: BusinessExtractionProposal[] = [
  { id: "proposal-nas-feedback", roomId: "room-nas-project", sourceMessageIds: ["message-nas-1", "message-nas-2"], proposalType: "sample_feedback", confidenceState: "needs_review", createdAt: "2026-08-06T09:20:00Z", status: "suggested", extractedFields: { sampleId: "SP-NAS-2407", sampleVersionId: "SP-NAS-2407-V2", summary: "Archive V2 five-wash and logo-position feedback", requestedChange: "Five-wash water-repellency check; move logo 2 mm higher", resolvedInVersionId: "SP-NAS-2407-V3" }, target: { kind: "sample_feedback", sampleId: "SP-NAS-2407", sampleVersionId: "SP-NAS-2407-V2" } },
  { id: "proposal-nas-price", roomId: "room-nas-project", sourceMessageIds: ["message-nas-3"], proposalType: "target_price", confidenceState: "clear", createdAt: "2026-08-06T09:30:00Z", status: "suggested", extractedFields: { currency: "USD", unitPrice: 0.82, quantity: 120000, unit: "pcs", context: "Recorded buyer target at annual volume; not an accepted quotation" }, target: { kind: "commercial_signal", projectId: 1 } },
  { id: "proposal-nas-action", roomId: "room-nas-project", sourceMessageIds: ["message-nas-3", "message-nas-4"], proposalType: "next_action", confidenceState: "needs_review", createdAt: "2026-08-06T09:36:00Z", status: "suggested", extractedFields: { title: "Follow up on V2 quote and testing-fee allocation", ownerActorId: "actor-sales-a", dueDate: "2026-08-12" }, target: { kind: "task", projectId: 1 } },
  { id: "proposal-efc-update", roomId: "room-efc-project", sourceMessageIds: ["message-efc-1", "message-efc-2"], proposalType: "customer_update", confidenceState: "clear", createdAt: "2026-08-07T11:00:00Z", status: "suggested", extractedFields: { summary: "Production scheduling follows the confirmed PO; carton marks remain open. The accepted quotation is unchanged." }, target: { kind: "account_activity", accountId: "client-efc" } },
  { id: "proposal-efc-meeting", roomId: "room-efc-project", sourceMessageIds: ["message-efc-1", "message-efc-2"], proposalType: "meeting_summary", confidenceState: "needs_review", createdAt: "2026-08-07T11:02:00Z", status: "suggested", extractedFields: { keyUpdates: "PO received; production scheduling in progress", customerRequirements: "Carton marks still to be confirmed", commercialSignals: "Accepted quotation remains unchanged", sampleChanges: "Approved sample remains the bulk reference", nextActions: "Confirm first production schedule", openQuestions: "Final outer-carton marks" }, target: { kind: "account_activity", accountId: "client-efc" } },
  { id: "proposal-eyw-contact", roomId: "room-eyw-project", sourceMessageIds: ["message-eyw-1"], proposalType: "contact_update", confidenceState: "needs_review", createdAt: "2026-08-08T08:15:00Z", status: "suggested", extractedFields: { contactId: "contact-deal-eyw-casey", name: "Casey Demo", jobTitle: "Product Developer", functionTag: "product_development" }, target: { kind: "contact", accountId: "client-eyw" } },
  { id: "proposal-eyw-referral", roomId: "room-eyw-project", sourceMessageIds: ["message-eyw-1"], proposalType: "relationship_update", confidenceState: "needs_review", createdAt: "2026-08-08T08:16:00Z", status: "suggested", extractedFields: { introducerContactId: "contact-eyw-mia", introducedContactId: "contact-deal-eyw-casey", recipientActorId: "actor-sales-c" }, target: { kind: "referral", accountId: "client-eyw" } },
  { id: "proposal-eyw-weight", roomId: "room-eyw-project", sourceMessageIds: ["message-eyw-2"], proposalType: "requirement_update", confidenceState: "ambiguous", createdAt: "2026-08-08T08:20:00Z", status: "suggested", extractedFields: { requirementId: "req-eyw-08", value: "180 gsm (pending customer confirmation)", note: "Internal discussion only; do not mark confirmed" }, target: { kind: "project_requirement", projectId: 3 } },
];

export const initialDealRoomState: DealRoomState = {
  rooms: [
    { id: "room-nas-project", accountId: "client-nas", projectId: 1, title: { zh: "NAS 防水拉链项目协作", en: "NAS Zipper Project Collaboration" }, status: "active", participantActorIds: ["actor-sales-a", "actor-sales-b", "actor-design-a"], createdAt: "2026-08-06T09:00:00Z", updatedAt: "2026-08-06T09:36:00Z" },
    { id: "room-efc-project", accountId: "client-efc", projectId: 2, title: { zh: "EFC 订单执行协作", en: "EFC Order Collaboration" }, status: "active", participantActorIds: ["actor-sales-a", "actor-sales-b", "actor-merch-a"], createdAt: "2026-08-07T10:30:00Z", updatedAt: "2026-08-07T11:02:00Z" },
    { id: "room-eyw-project", accountId: "client-eyw", projectId: 3, title: { zh: "EYW 多产品开发协作", en: "EYW Multi-product Collaboration" }, status: "active", participantActorIds: ["actor-sales-c", "actor-design-a", "actor-merch-a"], createdAt: "2026-08-08T08:00:00Z", updatedAt: "2026-08-08T08:20:00Z" },
    { id: "room-nas-account", accountId: "client-nas", title: { zh: "NAS 客户共享协作", en: "NAS Account Collaboration" }, status: "active", participantActorIds: ["actor-sales-a", "actor-sales-b"], createdAt: "2026-08-05T13:00:00Z", updatedAt: "2026-08-05T13:00:00Z" },
  ],
  messages: [
    { id: "message-nas-1", roomId: "room-nas-project", authorActorId: "actor-sales-b", createdAt: "2026-08-06T09:05:00Z", kind: "sample_feedback", content: { zh: "补录 V2 评审：客户要求完成 5 次水洗测试，并将 Logo 位置上移 2 mm。", en: "Archive the V2 review: the buyer asked for a five-wash test and a 2 mm higher logo position." }, businessContextRefs: [{ kind: "sample", id: "SP-NAS-2407" }, { kind: "sample_version", id: "SP-NAS-2407-V2" }] },
    { id: "message-nas-2", roomId: "room-nas-project", authorActorId: "actor-design-a", createdAt: "2026-08-06T09:15:00Z", kind: "internal_note", content: { zh: "V3 已完成这些调整并获确认。V2 反馈应归档为已在 V3 解决，不要修改 V3 签样。", en: "V3 addressed those changes and was approved. Archive the V2 feedback as resolved in V3; do not alter the signed V3 sample." }, attachmentIds: ["attachment-nas-drawing"], replyToMessageId: "message-nas-1", businessContextRefs: [{ kind: "sample_version", id: "SP-NAS-2407-V3" }] },
    { id: "message-nas-3", roomId: "room-nas-project", authorActorId: "actor-sales-a", createdAt: "2026-08-06T09:28:00Z", kind: "customer_update", content: { zh: "客户已记录的目标价格是 120,000 条年度量下 USD 0.82 / 条。它只是客户目标，并非已接受报价。", en: "The recorded buyer target is USD 0.82 per piece at 120,000 annual units. It is a customer target, not an accepted quote." }, businessContextRefs: [{ kind: "quotation", id: "QT-NAS-2407-V2" }] },
    { id: "message-nas-4", roomId: "room-nas-project", authorActorId: "actor-sales-b", createdAt: "2026-08-06T09:34:00Z", kind: "text", content: { zh: "下周跟进 V2 报价反馈及测试费用分摊，由销售 A 负责。", en: "Follow up on V2 quote feedback and testing-fee allocation next week; Sales A should own this." } },
    { id: "message-efc-1", roomId: "room-efc-project", authorActorId: "actor-merch-a", createdAt: "2026-08-07T10:35:00Z", kind: "meeting_note", content: { zh: "订单已收到，按确认样安排首批生产。外箱唛头仍待客户确认。", en: "The PO is received. Schedule first production against the approved sample; outer-carton marks still need client confirmation." }, attachmentIds: ["attachment-efc-note"] },
    { id: "message-efc-2", roomId: "room-efc-project", authorActorId: "actor-sales-a", createdAt: "2026-08-07T10:52:00Z", kind: "internal_note", content: { zh: "已接受的报价保持不变。请先确认生产排期，再向客户回复交付计划。", en: "The accepted quotation stays unchanged. Confirm production scheduling before replying with the delivery plan." }, businessContextRefs: [{ kind: "quotation", id: "QT-EFC-2411-V1" }] },
    { id: "message-eyw-1", roomId: "room-eyw-project", authorActorId: "actor-sales-c", createdAt: "2026-08-08T08:05:00Z", kind: "customer_update", content: { zh: "演示联系人 Mia 介绍了新的产品开发联系人 Casey Demo，并将其引荐给销售 C。先核对联系人身份再记录引荐。", en: "Demo contact Mia introduced new Product Developer Casey Demo to Sales C. Verify the contact before recording the referral." } },
    { id: "message-eyw-2", roomId: "room-eyw-project", authorActorId: "actor-design-a", createdAt: "2026-08-08T08:18:00Z", kind: "internal_note", content: { zh: "织带克重内部讨论目标为 180 gsm；客户尚未确认，不能将规格标记为已确认。", en: "The internal working weight for elastic tape is 180 gsm; the client has not confirmed it. Keep the specification pending." }, attachmentIds: ["attachment-eyw-swatch"] },
  ],
  attachments: [
    { id: "attachment-nas-drawing", roomId: "room-nas-project", kind: "technical_drawing", title: { zh: "V3 位置图示（演示）", en: "V3 position drawing (demo)" }, assetPath: "/deal-room/drawing-placeholder.svg", createdAt: "2026-08-06T09:15:00Z" },
    { id: "attachment-efc-note", roomId: "room-efc-project", kind: "meeting_note", title: { zh: "生产协调纪要（演示）", en: "Production coordination note (demo)" }, assetPath: "/deal-room/drawing-placeholder.svg", createdAt: "2026-08-07T10:35:00Z" },
    { id: "attachment-eyw-swatch", roomId: "room-eyw-project", kind: "sample_photo", title: { zh: "织带色样占位图", en: "Tape swatch placeholder" }, assetPath: "/deal-room/drawing-placeholder.svg", createdAt: "2026-08-08T08:18:00Z" },
  ],
  proposals,
  requirements: [],
  tasks: [],
  targetPriceSignals: [],
};

export const createDealRoomState = (): DealRoomState => structuredClone(initialDealRoomState);
