"use client";

import { type Dispatch, type FormEvent, useState } from "react";
import { Badge, Button, Modal } from "../ui/primitives";
import type { InterfaceLanguage } from "../layout/workspace-shell";
import type { OrderApproval, OrderIssue, ProductionMilestone, Shipment } from "../../lib/mock-data";
import { canCompleteOrder, formatOrderValue, getOrderHealth, type OrderAction, type OrderContext } from "./order-data";
import { ApprovalPanel, DeliveryShipmentPanel, OrderLifecycle, OrderOverview, OrderSidebar, OrderSummary, OrderTimeline, PaymentPanel, POContract, ProductionPanel } from "./order-panels";

type TabId = "overview" | "po" | "production" | "approval" | "logistics" | "payment" | "timeline";
type ModalKind = "update" | "issue" | "shipment" | "payment" | null;
const tabs: Array<{ id: TabId; label: string; en: string }> = [
  { id: "overview", label: "概览", en: "Overview" }, { id: "po", label: "PO 与合同", en: "PO & Contract" }, { id: "production", label: "生产", en: "Production" }, { id: "approval", label: "审批", en: "Approval" }, { id: "logistics", label: "交付与出货", en: "Delivery & Shipment" }, { id: "payment", label: "回款", en: "Payment" }, { id: "timeline", label: "时间线", en: "Timeline" },
];

export function OrderDetail({ context, language, dispatch, onBack, onClient, onProject, onQuotation, showToast }: { context: OrderContext; language: InterfaceLanguage; dispatch: Dispatch<OrderAction>; onBack: () => void; onClient: () => void; onProject: () => void; onQuotation: () => void; showToast: (message: string) => void }) {
  const [tab, setTab] = useState<TabId>("overview"); const [modal, setModal] = useState<ModalKind>(null); const [milestone, setMilestone] = useState<ProductionMilestone | null>(null); const [approval, setApproval] = useState<OrderApproval | null>(null);
  const order = context.order; const health = getOrderHealth(context); const isEn = language === "English";
  const notify = (message: string) => { setModal(null); setMilestone(null); setApproval(null); showToast(`${message} · Demo Workspace`); };
  const addUpdate = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); dispatch({ type: "event", id: order.id, event: { id: `oe-update-${crypto.randomUUID()}`, category: String(form.get("category")) as "Commercial" | "Production" | "Quality" | "Logistics" | "Payment", date: String(form.get("date")), title: String(form.get("title")), detail: String(form.get("detail")) } }); notify("订单更新已添加"); };
  const addIssue = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const issue: OrderIssue = { id: `issue-${crypto.randomUUID()}`, type: String(form.get("type")) as OrderIssue["type"], severity: String(form.get("severity")) as OrderIssue["severity"], issue: String(form.get("issue")), impact: String(form.get("impact")), owner: String(form.get("owner")), action: String(form.get("action")), blocking: form.get("blocking") === "on", resolved: false }; dispatch({ type: "issue", id: order.id, issue }); notify("执行问题已记录"); };
  const updateMilestone = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!milestone) return; const form = new FormData(event.currentTarget); dispatch({ type: "milestone", id: order.id, milestoneId: milestone.id, actualDate: String(form.get("actualDate")) }); notify(`${milestone.label} 已更新`); };
  const updateApproval = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!approval) return; const form = new FormData(event.currentTarget); dispatch({ type: "approval", id: order.id, approvalId: approval.id, status: String(form.get("status")) as OrderApproval["status"], note: String(form.get("note")) }); notify(`${approval.type} 已更新`); };
  const markShipment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const shipment: Shipment = { ...(context.shipment ?? { id: `sh-${order.id}`, purchaseOrderId: order.id, projectId: order.projectId }), method: String(form.get("method")), carrier: String(form.get("carrier")), reference: `DEMO-${String(form.get("reference")).replace(/^DEMO-/, "")}`, trackingNumber: `DEMO-${String(form.get("reference")).replace(/^DEMO-/, "")}`, destination: String(form.get("destination")), etd: String(form.get("etd")), eta: String(form.get("eta")), bookingDate: String(form.get("bookingDate")), cargoReadyDate: String(form.get("cargoReadyDate")), departedDate: String(form.get("etd")), status: "Shipped" }; dispatch({ type: "shipment", id: order.id, shipment }); notify("出货信息已记录"); };
  const recordPayment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); dispatch({ type: "payment", id: order.id, paidAmount: Number(form.get("paidAmount")), expectedPaymentDate: String(form.get("expectedDate")) }); notify("回款记录已更新"); };
  return <div className="order-workspace order-detail">
    <button className="back-link" onClick={onBack}>‹ 返回订单中心 / Back to Orders</button>
    <header className="order-header"><div><span className="eyebrow">ORDER EXECUTION WORKSPACE</span><div className="order-title-row"><h1>{order.poNumber}</h1><Badge>{order.currentStage}</Badge><span className={`order-health-label health-${health.status.toLowerCase().replaceAll(" ", "-")}`}>{health.status}</span></div><p><button onClick={onClient}>{context.client?.name}</button> · <button onClick={onProject}>{context.project?.code} / {context.project?.name}</button> · <button onClick={onQuotation}>{order.quotationId}</button></p><div className="order-header-facts"><span>{formatOrderValue(order.amount, order.currency)}</span><span>Owner · {order.owner}</span><span>Required Delivery · {order.deliveryDate || "待确认"}</span></div></div><div className="order-header-actions"><Button variant="secondary" onClick={() => setModal("update")}>添加更新 / Add Update</Button><Button variant="secondary" onClick={() => { const next = order.productionMilestones?.find((item) => item.status !== "Completed"); if (next) setMilestone(next); else showToast("当前没有可更新的生产节点"); }}>更新节点 / Milestone</Button><Button variant="secondary" onClick={() => setModal("issue")}>添加问题 / Add Issue</Button><Button variant="secondary" onClick={() => setModal("shipment")}>标记出货 / Shipment</Button><Button onClick={() => setModal("payment")}>记录回款 / Payment</Button></div></header>
    <OrderLifecycle context={context} /><OrderSummary context={context} />
    <div className="order-tabs" role="tablist">{tabs.map((item) => <button role="tab" aria-selected={tab === item.id} className={tab === item.id ? "active" : ""} key={item.id} onClick={() => setTab(item.id)}><strong>{item.label}</strong><span>{item.en}</span></button>)}</div>
    <div className="order-detail-grid"><main className="order-main-column">{tab === "overview" && <OrderOverview context={context} />}{tab === "po" && <POContract context={context} />}{tab === "production" && <ProductionPanel context={context} onUpdateMilestone={setMilestone} />}{tab === "approval" && <ApprovalPanel context={context} onApproval={setApproval} />}{tab === "logistics" && <DeliveryShipmentPanel context={context} />}{tab === "payment" && <PaymentPanel context={context} />}{tab === "timeline" && <OrderTimeline context={context} />}</main><aside className="order-side-column"><OrderSidebar context={context} onComplete={() => { if (!canCompleteOrder(context)) { showToast(isEn ? "Delivery, payment and blocking issues must be completed first." : "需先完成送达、回款并关闭阻塞问题"); return; } dispatch({ type: "complete", id: order.id }); showToast("订单已标记完成 · Demo Workspace"); }} /></aside></div>
    <p className="order-demo-note">Demo Workspace · Synthetic Data · 所有 Session 操作刷新后恢复。</p>

    {modal === "update" && <Modal title="添加订单更新 / Add Update" onClose={() => setModal(null)}><form className="modal-form order-modal-form" onSubmit={addUpdate}><div className="form-row"><label>分类 / Category<select name="category"><option>Commercial</option><option>Production</option><option>Quality</option><option>Logistics</option><option>Payment</option></select></label><label>日期 / Date<input name="date" type="date" required defaultValue="2026-08-05" /></label></div><label>标题 / Title<input name="title" required placeholder="例如：Material plan confirmed" /></label><label>说明 / Detail<textarea name="detail" rows={3} required /></label><ModalActions onClose={() => setModal(null)} label="保存更新 / Save Update" /></form></Modal>}
    {modal === "issue" && <Modal title="添加执行问题 / Add Issue" onClose={() => setModal(null)}><form className="modal-form order-modal-form" onSubmit={addIssue}><div className="form-row"><label>类型 / Type<select name="type"><option>Contract</option><option>Production</option><option>Quality</option><option>Testing</option><option>Delivery</option><option>Shipment</option><option>Payment</option><option>Customer Dependency</option></select></label><label>严重程度 / Severity<select name="severity"><option>Medium</option><option>High</option><option>Low</option></select></label></div><label>问题 / Issue<input name="issue" required /></label><label>影响 / Impact<textarea name="impact" rows={2} required /></label><div className="form-row"><label>负责人 / Owner<input name="owner" required defaultValue={order.owner} /></label><label className="order-checkbox"><input name="blocking" type="checkbox" />阻塞后续执行 / Blocking</label></div><label>建议行动 / Suggested Action<textarea name="action" rows={2} required /></label><ModalActions onClose={() => setModal(null)} label="记录问题 / Add Issue" /></form></Modal>}
    {modal === "shipment" && <Modal title="标记出货 / Mark Shipment" onClose={() => setModal(null)}><form className="modal-form order-modal-form" onSubmit={markShipment}><p className="sample-form-note">原型只保存演示物流信息，Reference 自动增加 DEMO 前缀。</p><div className="form-row"><label>运输方式 / Method<input name="method" required defaultValue={context.shipment?.method === "待确认 / Not confirmed" ? "Air Freight" : context.shipment?.method} /></label><label>承运方 / Carrier<input name="carrier" required defaultValue={context.shipment?.carrier ?? "Demo Carrier"} /></label></div><div className="form-row"><label>Booking Date<input name="bookingDate" type="date" required defaultValue="2026-11-12" /></label><label>Cargo Ready<input name="cargoReadyDate" type="date" required defaultValue="2026-11-15" /></label></div><div className="form-row"><label>ETD<input name="etd" type="date" required defaultValue={context.shipment?.etd} /></label><label>ETA<input name="eta" type="date" required defaultValue={context.shipment?.eta} /></label></div><label>Tracking / Reference<input name="reference" required defaultValue={context.shipment?.reference?.replace(/^DEMO-/, "") ?? `${order.poNumber}-SHIP`} /></label><label>目的地 / Destination<input name="destination" required defaultValue={context.shipment?.destination ?? order.shipTo} /></label><ModalActions onClose={() => setModal(null)} label="确认出货 / Mark Shipped" /></form></Modal>}
    {modal === "payment" && <Modal title="记录回款 / Record Payment" onClose={() => setModal(null)}><form className="modal-form order-modal-form" onSubmit={recordPayment}><p className="sample-form-note">仅记录原型金额，不连接银行、支付或真实财务系统。</p><label>累计已收 / Total Paid<input name="paidAmount" type="number" min="0" max={order.amount} step="0.01" required defaultValue={order.paidAmount ?? 0} /></label><label>预计回款日 / Expected Payment Date<input name="expectedDate" type="date" required defaultValue={order.expectedPaymentDate} /></label><ModalActions onClose={() => setModal(null)} label="保存回款 / Save Payment" /></form></Modal>}
    {milestone && <Modal title="更新生产节点 / Update Milestone" onClose={() => setMilestone(null)}><form className="modal-form order-modal-form" onSubmit={updateMilestone}><p><strong>{milestone.label}</strong><br />Target · {milestone.targetDate}<br />Dependency · {milestone.dependency}</p><label>实际完成日期 / Actual Date<input name="actualDate" type="date" required defaultValue="2026-08-05" /></label><ModalActions onClose={() => setMilestone(null)} label="标记完成 / Mark Completed" /></form></Modal>}
    {approval && <Modal title="记录审批 / Update Approval" onClose={() => setApproval(null)}><form className="modal-form order-modal-form" onSubmit={updateApproval}><p><strong>{approval.type}</strong><br />{approval.requirement}</p><label>状态 / Status<select name="status" defaultValue="Approved"><option>Approved</option><option>Pending</option><option>Revision Required</option><option>Not Required</option></select></label><label>说明 / Note<textarea name="note" rows={3} required defaultValue={approval.note} /></label><ModalActions onClose={() => setApproval(null)} label="保存审批 / Save Approval" /></form></Modal>}
  </div>;
}

function ModalActions({ onClose, label }: { onClose: () => void; label: string }) { return <div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>取消 / Cancel</Button><Button type="submit">{label}</Button></div>; }
