"use client";

import { type Dispatch, type FormEvent, useState } from "react";
import { Badge, Button, Modal } from "../ui/primitives";
import type { InterfaceLanguage } from "../layout/workspace-shell";
import type { OrderApproval, OrderIssue, ProductionMilestone, Shipment } from "../../lib/mock-data";
import { canCompleteOrder, formatOrderValue, getOrderHealth, type OrderAction, type OrderContext } from "./order-data";
import { ApprovalPanel, DeliveryShipmentPanel, OrderLifecycle, OrderOverview, OrderSidebar, OrderSummary, OrderTimeline, PaymentPanel, POContract, ProductionPanel } from "./order-panels";
import { useI18n } from "../providers/language-provider";
import type { Issue } from "../../lib/issues/types";
import { IssueBridge } from "../issues/issue-bridge";

type TabId = "overview" | "po" | "production" | "approval" | "logistics" | "payment" | "timeline";
type ModalKind = "update" | "issue" | "shipment" | "payment" | null;
const tabs: Array<{ id: TabId; key: "order.tabs.overview" | "order.tabs.poContract" | "order.tabs.production" | "order.tabs.approval" | "order.tabs.delivery" | "order.tabs.payment" | "order.tabs.timeline" }> = [
  { id: "overview", key: "order.tabs.overview" }, { id: "po", key: "order.tabs.poContract" }, { id: "production", key: "order.tabs.production" }, { id: "approval", key: "order.tabs.approval" }, { id: "logistics", key: "order.tabs.delivery" }, { id: "payment", key: "order.tabs.payment" }, { id: "timeline", key: "order.tabs.timeline" },
];

export function OrderDetail({ context, dispatch, onBack, onClient, onProject, onQuotation, issues, onOpenIssue, onCreateIssue, showToast }: { context: OrderContext; language: InterfaceLanguage; dispatch: Dispatch<OrderAction>; onBack: () => void; onClient: () => void; onProject: () => void; onQuotation: () => void; issues: Issue[]; onOpenIssue: (id: string) => void; onCreateIssue: () => void; showToast: (message: string) => void }) {
  const { language, t, label, text, formatDate } = useI18n();
  const [tab, setTab] = useState<TabId>("overview"); const [modal, setModal] = useState<ModalKind>(null); const [milestone, setMilestone] = useState<ProductionMilestone | null>(null); const [approval, setApproval] = useState<OrderApproval | null>(null);
  const order = context.order; const health = getOrderHealth(context, language);
  const notify = (message: string) => { setModal(null); setMilestone(null); setApproval(null); showToast(`${message} · ${t("common.demoWorkspace")}`); };
  const addUpdate = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); dispatch({ type: "event", id: order.id, event: { id: `oe-update-${crypto.randomUUID()}`, category: String(form.get("category")) as "Commercial" | "Production" | "Quality" | "Logistics" | "Payment", date: String(form.get("date")), title: String(form.get("title")), detail: String(form.get("detail")) } }); notify(t("order.addUpdateSuccess")); };
  const addIssue = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const issue: OrderIssue = { id: `issue-${crypto.randomUUID()}`, type: String(form.get("type")) as OrderIssue["type"], severity: String(form.get("severity")) as OrderIssue["severity"], issue: String(form.get("issue")), impact: String(form.get("impact")), owner: String(form.get("owner")), action: String(form.get("action")), blocking: form.get("blocking") === "on", resolved: false }; dispatch({ type: "issue", id: order.id, issue }); notify(t("order.addIssueSuccess")); };
  const updateMilestone = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!milestone) return; const form = new FormData(event.currentTarget); dispatch({ type: "milestone", id: order.id, milestoneId: milestone.id, actualDate: String(form.get("actualDate")) }); notify(`${text(milestone.label)} · ${t("actions.update")}`); };
  const updateApproval = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!approval) return; const form = new FormData(event.currentTarget); dispatch({ type: "approval", id: order.id, approvalId: approval.id, status: String(form.get("status")) as OrderApproval["status"], note: String(form.get("note")) }); notify(`${label(approval.type)} · ${t("actions.update")}`); };
  const markShipment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const shipment: Shipment = { ...(context.shipment ?? { id: `sh-${order.id}`, purchaseOrderId: order.id, projectId: order.projectId }), method: String(form.get("method")), carrier: String(form.get("carrier")), reference: `DEMO-${String(form.get("reference")).replace(/^DEMO-/, "")}`, trackingNumber: `DEMO-${String(form.get("reference")).replace(/^DEMO-/, "")}`, destination: String(form.get("destination")), etd: String(form.get("etd")), eta: String(form.get("eta")), bookingDate: String(form.get("bookingDate")), cargoReadyDate: String(form.get("cargoReadyDate")), departedDate: String(form.get("etd")), status: "Shipped" }; dispatch({ type: "shipment", id: order.id, shipment }); notify(t("order.shipmentSuccess")); };
  const recordPayment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); dispatch({ type: "payment", id: order.id, paidAmount: Number(form.get("paidAmount")), expectedPaymentDate: String(form.get("expectedDate")) }); notify(t("order.paymentSuccess")); };
  return <div className="order-workspace order-detail">
    <button className="back-link" onClick={onBack}>‹ {t("order.back")}</button>
    <header className="order-header"><div><span className="eyebrow">{t("order.executionWorkspace")}</span><div className="order-title-row"><h1>{order.poNumber}</h1><Badge>{label(order.currentStage)}</Badge><span className={`order-health-label health-${health.status.toLowerCase().replaceAll(" ", "-")}`}>{label(health.status)}</span></div><p><button onClick={onClient}>{text(context.client?.name ?? "")}</button> · <button onClick={onProject}>{context.project?.code} / {text(context.project?.name ?? "")}</button> · <button onClick={onQuotation}>{order.quotationId}</button></p><div className="order-header-facts"><span>{formatOrderValue(order.amount, order.currency)}</span><span>{t("common.owner")} · {text(order.owner)}</span><span>{t("order.requiredDelivery")} · {order.deliveryDate ? formatDate(order.deliveryDate) : t("common.notConfirmed")}</span></div></div><div className="order-header-actions"><Button variant="secondary" onClick={() => setModal("update")}>{t("order.addUpdate")}</Button><Button variant="secondary" onClick={() => { const next = order.productionMilestones?.find((item) => item.status !== "Completed"); if (next) setMilestone(next); else showToast(t("order.noMilestone")); }}>{t("order.updateMilestone")}</Button><Button variant="secondary" onClick={() => setModal("issue")}>{t("order.addIssue")}</Button><Button variant="secondary" onClick={() => setModal("shipment")}>{t("order.markShipment")}</Button><Button onClick={() => setModal("payment")}>{t("order.recordPayment")}</Button></div></header>
    <OrderLifecycle context={context} /><OrderSummary context={context} />
    <IssueBridge scope="order" issues={issues} onOpen={onOpenIssue} onCreate={onCreateIssue} />
    <div className="order-tabs" role="tablist">{tabs.map((item) => <button role="tab" aria-selected={tab === item.id} className={tab === item.id ? "active" : ""} key={item.id} onClick={() => setTab(item.id)}><strong>{t(item.key)}</strong></button>)}</div>
    <div className="order-detail-grid"><main className="order-main-column">{tab === "overview" && <OrderOverview context={context} />}{tab === "po" && <POContract context={context} />}{tab === "production" && <ProductionPanel context={context} onUpdateMilestone={setMilestone} />}{tab === "approval" && <ApprovalPanel context={context} onApproval={setApproval} />}{tab === "logistics" && <DeliveryShipmentPanel context={context} />}{tab === "payment" && <PaymentPanel context={context} />}{tab === "timeline" && <OrderTimeline context={context} />}</main><aside className="order-side-column"><OrderSidebar context={context} onComplete={() => { if (!canCompleteOrder(context)) { showToast(t("order.completeBlocked")); return; } dispatch({ type: "complete", id: order.id }); showToast(`${t("order.completeSuccess")} · ${t("common.demoWorkspace")}`); }} /></aside></div>
    <p className="order-demo-note">{t("common.demoWorkspace")} · {t("common.syntheticData")} · {t("common.sessionReset")}</p>

    {modal === "update" && <Modal title={t("order.updateModal")} onClose={() => setModal(null)}><form className="modal-form order-modal-form" onSubmit={addUpdate}><div className="form-row"><label>{t("common.category")}<select name="category">{["Commercial", "Production", "Quality", "Logistics", "Payment"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>{t("common.date")}<input name="date" type="date" required defaultValue="2026-08-05" /></label></div><label>{t("common.title")}<input name="title" required placeholder="Material plan confirmed" /></label><label>{t("common.description")}<textarea name="detail" rows={3} required /></label><ModalActions onClose={() => setModal(null)} label={t("order.saveUpdate")} /></form></Modal>}
    {modal === "issue" && <Modal title={t("order.issueModal")} onClose={() => setModal(null)}><form className="modal-form order-modal-form" onSubmit={addIssue}><div className="form-row"><label>{t("common.type")}<select name="type">{["Contract", "Production", "Quality", "Testing", "Delivery", "Shipment", "Payment", "Customer Dependency"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>{t("common.priority")}<select name="severity">{["Medium", "High", "Low"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label></div><label>{t("order.addIssue")}<input name="issue" required /></label><label>{t("common.impact")}<textarea name="impact" rows={2} required /></label><div className="form-row"><label>{t("common.owner")}<input name="owner" required defaultValue={order.owner} /></label><label className="order-checkbox"><input name="blocking" type="checkbox" />{t("order.blocking")}</label></div><label>{t("order.suggestedAction")}<textarea name="action" rows={2} required /></label><ModalActions onClose={() => setModal(null)} label={t("order.recordIssue")} /></form></Modal>}
    {modal === "shipment" && <Modal title={t("order.shipmentModal")} onClose={() => setModal(null)}><form className="modal-form order-modal-form" onSubmit={markShipment}><p className="sample-form-note">{t("order.prototypeLogistics")}</p><div className="form-row"><label>{t("common.method")}<input name="method" required defaultValue={context.shipment?.method === "待确认 / Not confirmed" ? "Air Freight" : context.shipment?.method} /></label><label>{t("common.carrier")}<input name="carrier" required defaultValue={context.shipment?.carrier ?? "Demo Carrier"} /></label></div><div className="form-row"><label>{t("order.bookingDate")}<input name="bookingDate" type="date" required defaultValue="2026-11-12" /></label><label>{t("order.cargoReadyDate")}<input name="cargoReadyDate" type="date" required defaultValue="2026-11-15" /></label></div><div className="form-row"><label>ETD<input name="etd" type="date" required defaultValue={context.shipment?.etd} /></label><label>ETA<input name="eta" type="date" required defaultValue={context.shipment?.eta} /></label></div><label>{t("order.trackingReference")}<input name="reference" required defaultValue={context.shipment?.reference?.replace(/^DEMO-/, "") ?? `${order.poNumber}-SHIP`} /></label><label>{t("common.destination")}<input name="destination" required defaultValue={context.shipment?.destination ?? order.shipTo} /></label><ModalActions onClose={() => setModal(null)} label={t("order.confirmShipment")} /></form></Modal>}
    {modal === "payment" && <Modal title={t("order.paymentModal")} onClose={() => setModal(null)}><form className="modal-form order-modal-form" onSubmit={recordPayment}><p className="sample-form-note">{t("order.prototypePayment")}</p><label>{t("order.totalPaid")}<input name="paidAmount" type="number" min="0" max={order.amount} step="0.01" required defaultValue={order.paidAmount ?? 0} /></label><label>{t("order.expectedPaymentDate")}<input name="expectedDate" type="date" required defaultValue={order.expectedPaymentDate} /></label><ModalActions onClose={() => setModal(null)} label={t("order.savePayment")} /></form></Modal>}
    {milestone && <Modal title={t("order.milestoneModal")} onClose={() => setMilestone(null)}><form className="modal-form order-modal-form" onSubmit={updateMilestone}><p><strong>{text(milestone.label)}</strong><br />{t("common.target")} · {formatDate(milestone.targetDate)}<br />{t("common.dependency")} · {text(milestone.dependency ?? "")}</p><label>{t("order.actualDate")}<input name="actualDate" type="date" required defaultValue="2026-08-05" /></label><ModalActions onClose={() => setMilestone(null)} label={t("actions.markCompleted")} /></form></Modal>}
    {approval && <Modal title={t("order.approvalModal")} onClose={() => setApproval(null)}><form className="modal-form order-modal-form" onSubmit={updateApproval}><p><strong>{label(approval.type)}</strong><br />{text(approval.requirement)}</p><label>{t("common.status")}<select name="status" defaultValue="Approved">{["Approved", "Pending", "Revision Required", "Not Required"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>{t("common.description")}<textarea name="note" rows={3} required defaultValue={approval.note} /></label><ModalActions onClose={() => setApproval(null)} label={t("order.saveApproval")} /></form></Modal>}
  </div>;
}

function ModalActions({ onClose, label }: { onClose: () => void; label: string }) { const { t } = useI18n(); return <div className="modal-actions"><Button type="button" variant="ghost" onClick={onClose}>{t("actions.cancel")}</Button><Button type="submit">{label}</Button></div>; }
