import type { BusinessCase, ProjectStage } from "./types";
import { withSampleDevelopment } from "./sample-development";
import { withQuotationDevelopment } from "./quotation-development";
import { withOrderExecution } from "./order-execution";
import { withProductLibraryLinks } from "./product-library-links";

export const projectStages: ProjectStage[] = [
  "新询盘",
  "需求确认",
  "打样中",
  "报价中",
  "谈判中",
  "已确认订单",
  "暂停或流失",
];

const caseA: BusinessCase = {
  client: {
    id: "client-nas",
    code: "NAS",
    name: "North American Sportswear Brand",
    country: "美国",
    region: "西雅图",
    type: "运动服装品牌",
    status: "活跃",
    currency: "USD",
    paymentTerm: "T/T 30% deposit, 70% before shipment",
    communicationLanguage: "English",
    primaryContactId: "contact-nas-olivia",
    lastContactAt: "2026-08-01T16:20:00Z",
    preferences: ["哑光外观", "功能测试数据", "简洁英文邮件", "阶梯报价"],
  },
  contacts: [
    {
      id: "contact-nas-olivia",
      clientId: "client-nas",
      name: "Olivia Reed",
      title: "Product Developer",
      email: "olivia.reed@example-client.com",
      isPrimary: true,
      department: "Material Development",
      decisionRole: "Technical Approver",
      influenceLevel: "High",
      relationshipStrength: "Strong",
      lastContactAt: "2026-08-01T16:20:00Z",
    },
    { id: "contact-nas-ethan", clientId: "client-nas", name: "Ethan Cole", title: "Sourcing Manager", email: "ethan.cole@example-client.com", isPrimary: false, department: "Sourcing", decisionRole: "Buyer", influenceLevel: "Medium", relationshipStrength: "Developing", lastContactAt: "2026-07-30T13:20:00Z" },
  ],
  project: {
    id: 1,
    clientId: "client-nas",
    code: "NAS-2407",
    name: "北美运动服装品牌——防水拉链开发",
    customer: "North American Sportswear Brand",
    region: "美国 · 西雅图",
    product: "防水尼龙拉链",
    stage: "谈判中",
    lifecycleStage: "negotiation",
    progress: "V3 样品已确认，V2 报价已发送，正在沟通目标价格与测试成本",
    owner: "陈晨",
    ownerActorId: "actor-sales-a",
    next: "确认客户对 V2 阶梯报价的反馈并推进价格收口",
    updated: "今天 10:24",
    lastUpdatedAt: "2026-08-02T10:24:00+08:00",
    quantity: "120,000 条 / 年",
    delivery: "2026 年 10 月 15 日",
    health: "关注",
    contact: "Olivia Reed · Product Developer",
    email: "olivia.reed@example-client.com",
    initials: "NA",
    color: "#275d84",
    currentSummary: "V3 功能样已获客户确认，项目已进入 V2 报价谈判。测试标准已对齐，目标价格与首单长度配比仍待确认。",
    confirmedInformation: [
      "#5 TPU 膜防水尼龙拉链",
      "Black C 与 Cool Gray 11 C",
      "58 cm、64 cm、72 cm 三种长度",
      "V3 样品外观与功能已确认",
      "AATCC 22，5 次水洗后不低于 80 分",
    ],
    pendingInformation: ["客户最终可接受单价", "首单各长度数量比例", "大货包装与条码格式"],
    risks: ["客户目标价低于 V2 报价", "专项测试费用的承担方式尚未确认"],
    nextActions: ["跟进 V2 报价反馈", "确认首单数量结构", "书面确认测试费用"],
  },
  requirements: [
    { id: "req-nas-01", projectId: 1, product: "防水尼龙拉链", field: "产品类型", fieldEn: "Product Type", value: "TPU 膜防水尼龙拉链", status: "已确认", source: "客户确认", updatedAt: "2026-07-12" },
    { id: "req-nas-02", projectId: 1, product: "防水尼龙拉链", field: "材质", fieldEn: "Material", value: "尼龙链牙 + TPU 膜", status: "已确认", source: "客户确认", updatedAt: "2026-07-12" },
    { id: "req-nas-03", projectId: 1, product: "防水尼龙拉链", field: "颜色", fieldEn: "Color", value: "Black C、Cool Gray 11 C", status: "已确认", source: "样品反馈", updatedAt: "2026-07-28" },
    { id: "req-nas-04", projectId: 1, product: "防水尼龙拉链", field: "尺寸", fieldEn: "Size", value: "#5", status: "已确认", source: "客户确认", updatedAt: "2026-07-12" },
    { id: "req-nas-05", projectId: 1, product: "防水尼龙拉链", field: "拉链长度", fieldEn: "Zipper Length", value: "58 cm / 64 cm / 72 cm", status: "已确认", source: "客户确认", updatedAt: "2026-07-12" },
    { id: "req-nas-06", projectId: 1, product: "防水尼龙拉链", field: "表面处理", fieldEn: "Surface Finish", value: "哑光膜面", status: "已确认", source: "样品反馈", updatedAt: "2026-07-28" },
    { id: "req-nas-07", projectId: 1, product: "防水尼龙拉链", field: "定制 Logo", fieldEn: "Customized Logo", value: "拉片激光雕刻客户代号", status: "已确认", source: "样品反馈", updatedAt: "2026-07-31" },
    { id: "req-nas-08", projectId: 1, product: "防水尼龙拉链", field: "预计数量", fieldEn: "Estimated Quantity", value: "120,000 条 / 年", status: "已确认", source: "客户询盘", updatedAt: "2026-07-10" },
    { id: "req-nas-09", projectId: 1, product: "防水尼龙拉链", field: "测试标准", fieldEn: "Testing Standard", value: "AATCC 22；5 次水洗后 ≥ 80 分", status: "已确认", source: "客户确认", updatedAt: "2026-07-31" },
    { id: "req-nas-10", projectId: 1, product: "防水尼龙拉链", field: "目标价格", fieldEn: "Target Price", value: "USD 0.82 / 条", status: "待确认", source: "客户询盘", updatedAt: "2026-08-01" },
    { id: "req-nas-11", projectId: 1, product: "防水尼龙拉链", field: "目标交期", fieldEn: "Target Delivery Date", value: "2026-10-15", status: "已确认", source: "客户询盘", updatedAt: "2026-07-10" },
  ],
  samples: [
    {
      id: "SP-NAS-2407",
      clientId: "client-nas",
      projectId: 1,
      product: "防水尼龙拉链",
      currentVersionId: "SP-NAS-2407-V3",
      currentVersion: "V3",
      status: "已确认",
      createdAt: "2026-07-12",
      sentDate: "2026-07-30",
      feedbackStatus: "客户已确认",
      nextAction: "依据确认样准备最终报价与大货规格表",
      specs: { size: "#5", material: "Nylon + TPU", color: "Black C / Cool Gray 11 C", length: "58 / 64 / 72 cm", logo: "Laser engraving" },
    },
  ],
  sampleVersions: [
    { id: "SP-NAS-2407-V1", sampleId: "SP-NAS-2407", projectId: 1, version: "V1", createdAt: "2026-07-12", sentDate: "2026-07-14", status: "需修改", summary: "首版外观与颜色样", changes: ["初始 TPU 膜配方", "标准拉片，无 Logo"] },
    { id: "SP-NAS-2407-V2", sampleId: "SP-NAS-2407", projectId: 1, version: "V2", createdAt: "2026-07-20", sentDate: "2026-07-24", status: "需修改", summary: "调整膜面光泽与灰色色相", changes: ["降低膜面光泽", "Cool Gray 色相调暖", "增加激光 Logo 位置样"] },
    { id: "SP-NAS-2407-V3", sampleId: "SP-NAS-2407", projectId: 1, version: "V3", createdAt: "2026-07-29", sentDate: "2026-07-30", status: "已确认", summary: "确认版功能样", changes: ["采用 5 次水洗测试配方", "Logo 位置上移 2 mm", "锁定哑光表面"] },
  ],
  sampleFeedback: [
    { id: "fb-nas-v1-01", sampleId: "SP-NAS-2407", sampleVersionId: "SP-NAS-2407-V1", projectId: 1, receivedAt: "2026-07-18", author: "Olivia Reed", channel: "Email", summary: "颜色过深且膜面偏亮", details: "客户认为黑色可接受，但灰色偏冷，膜面光泽不符合哑光方向。", requiresRevision: true },
    { id: "fb-nas-v2-01", sampleId: "SP-NAS-2407", sampleVersionId: "SP-NAS-2407-V2", projectId: 1, receivedAt: "2026-07-28", author: "Olivia Reed", channel: "WhatsApp", summary: "颜色通过，要求加强洗后测试", details: "客户接受颜色与光泽，希望确认 5 次水洗后的防泼水等级，并调整 Logo 位置。", requiresRevision: true },
    { id: "fb-nas-v3-01", sampleId: "SP-NAS-2407", sampleVersionId: "SP-NAS-2407-V3", projectId: 1, receivedAt: "2026-07-31", author: "Olivia Reed", channel: "Email", summary: "V3 样品确认", details: "客户确认 V3 外观、Logo 位置及测试结果，可进入最终报价。", requiresRevision: false },
  ],
  quotations: [
    { id: "QT-NAS-2407-V1", clientId: "client-nas", projectId: 1, version: "V1", product: "防水尼龙拉链", quantity: 120000, unit: "条", unitPrice: 0.91, currency: "USD", status: "Rejected", validUntil: "2026-08-20", issuedAt: "2026-07-29", targetPrice: 0.82, internalTargetPrice: 0.86, moq: 80000, incoterm: "FOB Ningbo", clientFeedback: "客户认为单价高于预算，希望结合年度数量重新评估。" },
    { id: "QT-NAS-2407-V2", clientId: "client-nas", projectId: 1, version: "V2", product: "防水尼龙拉链", quantity: 120000, unit: "条", unitPrice: 0.88, currency: "USD", status: "Negotiating", validUntil: "2026-08-31", issuedAt: "2026-08-02", targetPrice: 0.82, internalTargetPrice: 0.86, moq: 80000, incoterm: "FOB Ningbo", clientFeedback: "V2 已发送，等待客户确认年度数量与测试费用分摊。" },
  ],
  quotationTiers: [
    { id: "tier-nas-v1-80", quotationId: "QT-NAS-2407-V1", minimumQuantity: 80000, maximumQuantity: 119999, unitPrice: 0.94, currency: "USD" },
    { id: "tier-nas-v1-120", quotationId: "QT-NAS-2407-V1", minimumQuantity: 120000, maximumQuantity: 199999, unitPrice: 0.91, currency: "USD" },
    { id: "tier-nas-v1-200", quotationId: "QT-NAS-2407-V1", minimumQuantity: 200000, unitPrice: 0.87, currency: "USD" },
    { id: "tier-nas-v2-80", quotationId: "QT-NAS-2407-V2", minimumQuantity: 80000, maximumQuantity: 119999, unitPrice: 0.92, currency: "USD", note: "专项测试费另计" },
    { id: "tier-nas-v2-120", quotationId: "QT-NAS-2407-V2", minimumQuantity: 120000, maximumQuantity: 199999, unitPrice: 0.88, currency: "USD" },
    { id: "tier-nas-v2-200", quotationId: "QT-NAS-2407-V2", minimumQuantity: 200000, unitPrice: 0.85, currency: "USD", note: "采用标准包装" },
  ],
  negotiationRecords: [
    { id: "neg-nas-01", quotationId: "QT-NAS-2407-V1", projectId: 1, recordedAt: "2026-07-30", direction: "客户反馈", summary: "客户提出 USD 0.82 / 条的目标价，并表示年度需求可能达到 200,000 条。", nextAction: "核实年度预测并准备数量阶梯" },
    { id: "neg-nas-02", quotationId: "QT-NAS-2407-V1", projectId: 1, recordedAt: "2026-07-31", direction: "内部建议", summary: "建议以标准包装、年度采购承诺和专项测试费分开列示作为让步条件。", nextAction: "形成 V2 报价" },
    { id: "neg-nas-03", quotationId: "QT-NAS-2407-V2", projectId: 1, recordedAt: "2026-08-02", direction: "销售回复", summary: "已发送 V2 阶梯报价，120,000 条档位为 USD 0.88 / 条。", nextAction: "跟进客户对数量承诺和测试费用的回复" },
  ],
  purchaseOrders: [],
  orderLines: [],
  contracts: [],
  deliveries: [],
  shipments: [],
  communications: [
    { id: "com-nas-01", projectId: 1, clientId: "client-nas", type: "客户邮件", occurredAt: "2026-07-10T09:10:00Z", author: "Olivia Reed", subject: "Waterproof zipper development inquiry", content: "Client shared the initial waterproof zipper requirements and annual estimate.", language: "英文" },
    { id: "com-nas-02", projectId: 1, clientId: "client-nas", relatedEntityType: "sample", relatedEntityId: "SP-NAS-2407-V1", type: "样品反馈", occurredAt: "2026-07-18T15:30:00Z", author: "Olivia Reed", subject: "V1 sample feedback", content: "The gray color looks too cool and the film surface is more glossy than expected.", language: "英文" },
    { id: "com-nas-03", projectId: 1, clientId: "client-nas", relatedEntityType: "quotation", relatedEntityId: "QT-NAS-2407-V1", type: "报价反馈", occurredAt: "2026-07-30T13:20:00Z", author: "Olivia Reed", subject: "Quotation V1 feedback", content: "客户提出目标价，并希望按年度数量重新计算。", language: "中英对照" },
  ],
  tasks: [
    { id: "task-nas-01", projectId: 1, relatedEntityType: "quotation", relatedEntityId: "QT-NAS-2407-V2", title: "跟进 V2 报价反馈", owner: "陈晨", priority: "P1", dueDate: "2026-08-04", status: "进行中" },
    { id: "task-nas-02", projectId: 1, relatedEntityType: "quotation", relatedEntityId: "QT-NAS-2407-V2", title: "确认测试费用承担方式", owner: "陈晨", priority: "P1", dueDate: "2026-08-05", status: "待处理" },
  ],
  timeline: [
    { id: "tl-nas-01", projectId: 1, clientId: "client-nas", type: "inquiry", occurredAt: "2026-07-10", displayDate: "7 月 10 日", title: "收到客户询盘", description: "收到防水尼龙拉链开发需求及年度数量预测。", icon: "✉" },
    { id: "tl-nas-02", projectId: 1, clientId: "client-nas", type: "requirement", occurredAt: "2026-07-12", displayDate: "7 月 12 日", title: "建立产品需求", description: "确认尺寸、颜色、长度和初始测试方向。", icon: "▣" },
    { id: "tl-nas-03", projectId: 1, clientId: "client-nas", type: "sample", relatedEntityId: "SP-NAS-2407-V1", occurredAt: "2026-07-12", displayDate: "7 月 12 日", title: "创建 Sample V1", description: "创建首版外观与颜色样。", icon: "◈" },
    { id: "tl-nas-04", projectId: 1, clientId: "client-nas", type: "communication", relatedEntityId: "fb-nas-v1-01", occurredAt: "2026-07-18", displayDate: "7 月 18 日", title: "收到 V1 客户反馈", description: "客户反馈灰色偏冷、膜面偏亮。", icon: "✉" },
    { id: "tl-nas-05", projectId: 1, clientId: "client-nas", type: "sample", relatedEntityId: "SP-NAS-2407-V2", occurredAt: "2026-07-20", displayDate: "7 月 20 日", title: "创建 Sample V2", description: "调整颜色、光泽与 Logo 位置。", icon: "◈" },
    { id: "tl-nas-06", projectId: 1, clientId: "client-nas", type: "sample", relatedEntityId: "SP-NAS-2407-V3", occurredAt: "2026-07-29", displayDate: "7 月 29 日", title: "创建 Sample V3", description: "采用确认测试配方并完成 Logo 调整。", icon: "◈" },
    { id: "tl-nas-07", projectId: 1, clientId: "client-nas", type: "quotation", relatedEntityId: "QT-NAS-2407-V1", occurredAt: "2026-07-29", displayDate: "7 月 29 日", title: "发送 Quotation V1", description: "发送首版三档数量报价。", icon: "¥" },
    { id: "tl-nas-08", projectId: 1, clientId: "client-nas", type: "negotiation", relatedEntityId: "neg-nas-01", occurredAt: "2026-07-30", displayDate: "7 月 30 日", title: "进入价格谈判", description: "客户提出目标价并讨论年度采购承诺。", icon: "↔" },
    { id: "tl-nas-09", projectId: 1, clientId: "client-nas", type: "communication", relatedEntityId: "fb-nas-v3-01", occurredAt: "2026-07-31", displayDate: "7 月 31 日", title: "Sample V3 获确认", description: "客户确认外观、Logo 位置及功能测试结果。", icon: "✓" },
    { id: "tl-nas-10", projectId: 1, clientId: "client-nas", type: "quotation", relatedEntityId: "QT-NAS-2407-V2", occurredAt: "2026-08-02", displayDate: "8 月 2 日", title: "发送 Quotation V2", description: "按数量承诺与标准包装条件更新报价。", icon: "¥" },
  ],
  weeklyReports: [],
  aiInsights: [
    { id: "ai-nas-project", projectId: 1, relatedEntityType: "project", relatedEntityId: "NAS-2407", title: "项目摘要", content: "样品已确认，当前重点是收口 V2 报价及测试费用条件。", generatedAt: "2026-08-02", mode: "mock" },
    { id: "ai-nas-quote", projectId: 1, relatedEntityType: "quotation", relatedEntityId: "QT-NAS-2407-V2", title: "模拟议价建议", content: "优先交换年度采购承诺、标准包装和测试费单列，不直接承诺未记录的新价格。", generatedAt: "2026-08-02", mode: "mock" },
  ],
};

const caseB: BusinessCase = {
  client: {
    id: "client-efc",
    code: "EFC",
    name: "European Fashion Client",
    country: "法国",
    region: "巴黎",
    type: "时尚品牌采购商",
    status: "活跃",
    currency: "EUR",
    paymentTerm: "T/T 30 days after shipment",
    communicationLanguage: "English",
    primaryContactId: "contact-efc-camille",
    lastContactAt: "2026-08-05T09:40:00Z",
    preferences: ["古铜色表面", "REACH 合规", "报价费用拆分", "邮件确认关键节点"],
  },
  contacts: [
    { id: "contact-efc-camille", clientId: "client-efc", name: "Camille Bernard", title: "Buyer", email: "camille.bernard@example-client.com", isPrimary: true, department: "Sourcing", decisionRole: "Buyer", influenceLevel: "High", relationshipStrength: "Strong", lastContactAt: "2026-08-05T09:40:00Z" },
    { id: "contact-efc-sophie", clientId: "client-efc", name: "Sophie Laurent", title: "Head of Sourcing", email: "sophie.laurent@example-client.com", isPrimary: false, department: "Management", decisionRole: "Decision Maker", influenceLevel: "High", relationshipStrength: "Developing", lastContactAt: "2026-07-24T10:15:00Z" },
    { id: "contact-efc-marcel", clientId: "client-efc", name: "Marcel Durand", title: "Production Coordinator", email: "marcel.durand@example-client.com", isPrimary: false, department: "Production", decisionRole: "User", influenceLevel: "Medium", relationshipStrength: "Developing", lastContactAt: "2026-08-02T12:10:00Z" },
  ],
  project: {
    id: 2,
    clientId: "client-efc",
    code: "EFC-2411",
    name: "欧洲时尚品牌——金属纽扣项目",
    customer: "European Fashion Client",
    region: "法国 · 巴黎",
    product: "锌合金四合扣",
    stage: "已确认订单",
    lifecycleStage: "po",
    progress: "客户已确认样品和报价，PO 已收到，合同已确认并进入计划交付",
    owner: "王璐",
    ownerActorId: "actor-sales-b",
    next: "确认首批生产排期并在 8 月 12 日前回复交付计划",
    updated: "昨天 16:40",
    lastUpdatedAt: "2026-08-05T16:40:00+08:00",
    quantity: "80,000 套",
    delivery: "2026 年 11 月 20 日",
    health: "良好",
    contact: "Camille Bernard · Buyer",
    email: "camille.bernard@example-client.com",
    initials: "EU",
    color: "#7d5d47",
    currentSummary: "确认样和 Accepted Quotation 已转为正式 PO，合同已确认，当前等待生产排期与计划交付。",
    confirmedInformation: ["锌合金四合扣", "古铜色无镍电镀", "REACH 测试要求", "80,000 套 PO", "2026-11-20 交付"],
    pendingInformation: ["最终外箱唛头", "首批生产完成日期"],
    risks: ["外箱唛头未确认，暂不影响生产"],
    nextActions: ["确认生产排期", "发送计划交付节点", "跟进外箱唛头"],
  },
  requirements: [
    { id: "req-efc-01", projectId: 2, product: "锌合金四合扣", field: "产品类型", fieldEn: "Product Type", value: "锌合金四合扣", status: "已确认", source: "客户确认", updatedAt: "2026-07-05" },
    { id: "req-efc-02", projectId: 2, product: "锌合金四合扣", field: "尺寸", fieldEn: "Size", value: "15 mm", status: "已确认", source: "客户确认", updatedAt: "2026-07-05" },
    { id: "req-efc-03", projectId: 2, product: "锌合金四合扣", field: "表面处理", fieldEn: "Surface Finish", value: "古铜色无镍电镀", status: "已确认", source: "样品反馈", updatedAt: "2026-07-18" },
    { id: "req-efc-04", projectId: 2, product: "锌合金四合扣", field: "定制 Logo", fieldEn: "Customized Logo", value: "帽面压印匿名品牌字母", status: "已确认", source: "样品反馈", updatedAt: "2026-07-18" },
    { id: "req-efc-05", projectId: 2, product: "锌合金四合扣", field: "测试标准", fieldEn: "Testing Standard", value: "REACH SVHC + Nickel Release", status: "已确认", source: "客户确认", updatedAt: "2026-07-22" },
    { id: "req-efc-06", projectId: 2, product: "锌合金四合扣", field: "预计数量", fieldEn: "Estimated Quantity", value: "80,000 套", status: "已确认", source: "客户确认", updatedAt: "2026-07-22" },
    { id: "req-efc-07", projectId: 2, product: "锌合金四合扣", field: "目标交期", fieldEn: "Target Delivery Date", value: "2026-11-20", status: "已确认", source: "客户确认", updatedAt: "2026-07-22" },
  ],
  samples: [
    { id: "SP-EFC-2411", clientId: "client-efc", projectId: 2, product: "锌合金四合扣", currentVersionId: "SP-EFC-2411-V2", currentVersion: "V2", status: "已确认", createdAt: "2026-07-08", sentDate: "2026-07-16", feedbackStatus: "客户已确认", nextAction: "作为大货签样标准归档", specs: { size: "15 mm", material: "Zinc alloy", finish: "Antique brass, nickel free", logo: "Debossed initials" } },
  ],
  sampleVersions: [
    { id: "SP-EFC-2411-V1", sampleId: "SP-EFC-2411", projectId: 2, version: "V1", createdAt: "2026-07-08", sentDate: "2026-07-10", status: "需修改", summary: "首版古铜色样", changes: ["初版 Logo 深度", "标准古铜色"] },
    { id: "SP-EFC-2411-V2", sampleId: "SP-EFC-2411", projectId: 2, version: "V2", createdAt: "2026-07-14", sentDate: "2026-07-16", status: "已确认", summary: "客户确认样", changes: ["Logo 压印加深 0.2 mm", "表面颜色降低红调"] },
  ],
  sampleFeedback: [
    { id: "fb-efc-v1-01", sampleId: "SP-EFC-2411", sampleVersionId: "SP-EFC-2411-V1", projectId: 2, receivedAt: "2026-07-13", author: "Camille Bernard", channel: "Email", summary: "Logo 深度不足，颜色略偏红", details: "客户要求加深 Logo 压印并降低古铜色红调。", requiresRevision: true },
    { id: "fb-efc-v2-01", sampleId: "SP-EFC-2411", sampleVersionId: "SP-EFC-2411-V2", projectId: 2, receivedAt: "2026-07-18", author: "Camille Bernard", channel: "Email", summary: "V2 样品确认", details: "客户确认 V2 外观、结构和表面处理，允许进入报价。", requiresRevision: false },
  ],
  quotations: [
    { id: "QT-EFC-2411-V1", clientId: "client-efc", projectId: 2, version: "V1", product: "锌合金四合扣", quantity: 80000, unit: "套", unitPrice: 0.34, currency: "EUR", status: "Accepted", validUntil: "2026-08-30", issuedAt: "2026-07-22", targetPrice: 0.34, internalTargetPrice: 0.32, moq: 50000, incoterm: "FOB Ningbo", clientFeedback: "客户接受报价，要求合同列明测试费用已包含。" },
  ],
  quotationTiers: [
    { id: "tier-efc-50", quotationId: "QT-EFC-2411-V1", minimumQuantity: 50000, maximumQuantity: 79999, unitPrice: 0.36, currency: "EUR" },
    { id: "tier-efc-80", quotationId: "QT-EFC-2411-V1", minimumQuantity: 80000, maximumQuantity: 149999, unitPrice: 0.34, currency: "EUR" },
    { id: "tier-efc-150", quotationId: "QT-EFC-2411-V1", minimumQuantity: 150000, unitPrice: 0.31, currency: "EUR" },
  ],
  negotiationRecords: [
    { id: "neg-efc-01", quotationId: "QT-EFC-2411-V1", projectId: 2, recordedAt: "2026-07-24", direction: "客户反馈", summary: "客户接受 80,000 套价格，要求确认报价含 REACH 与 Nickel Release 测试费用。", nextAction: "在合同中列明测试费用已包含" },
  ],
  purchaseOrders: [
    { id: "po-efc-2411", poNumber: "PO-EFC-240802", clientId: "client-efc", projectId: 2, quotationId: "QT-EFC-2411-V1", amount: 27200, currency: "EUR", poDate: "2026-08-02", deliveryDate: "2026-11-20", currentStage: "Contract", health: "良好", owner: "王璐", paymentStatus: "未到期" },
  ],
  orderLines: [
    { id: "line-efc-01", purchaseOrderId: "po-efc-2411", product: "锌合金四合扣", specification: "15 mm · 古铜色无镍电镀 · 定制 Logo", quantity: 80000, unit: "套", unitPrice: 0.34, amount: 27200 },
  ],
  contracts: [
    { id: "ct-efc-240805", purchaseOrderId: "po-efc-2411", projectId: 2, contractNumber: "CT-EFC-240805", status: "Confirmed", confirmedAt: "2026-08-05", owner: "王璐" },
  ],
  deliveries: [
    { id: "dl-efc-241115", purchaseOrderId: "po-efc-2411", projectId: 2, plannedDate: "2026-11-15", quantity: 80000, status: "Pending" },
  ],
  shipments: [
    { id: "sh-efc-241118", purchaseOrderId: "po-efc-2411", projectId: 2, method: "Air Freight", destination: "Paris, France", etd: "2026-11-18", eta: "2026-11-20", status: "Pending" },
  ],
  communications: [
    { id: "com-efc-01", projectId: 2, clientId: "client-efc", relatedEntityType: "sample", relatedEntityId: "SP-EFC-2411-V2", type: "样品反馈", occurredAt: "2026-07-18", author: "Camille Bernard", subject: "V2 approval", content: "The V2 sample is approved for quotation.", language: "英文" },
    { id: "com-efc-02", projectId: 2, clientId: "client-efc", relatedEntityType: "po", relatedEntityId: "po-efc-2411", type: "客户邮件", occurredAt: "2026-08-02", author: "Camille Bernard", subject: "Official PO", content: "客户发送正式 PO，并确认要求的交付日期。", language: "中英对照" },
  ],
  tasks: [
    { id: "task-efc-01", projectId: 2, relatedEntityType: "po", relatedEntityId: "po-efc-2411", title: "确认首批生产排期", owner: "王璐", priority: "P1", dueDate: "2026-08-12", status: "进行中" },
    { id: "task-efc-02", projectId: 2, relatedEntityType: "delivery", relatedEntityId: "dl-efc-241115", title: "跟进客户外箱唛头", owner: "王璐", priority: "P2", dueDate: "2026-08-15", status: "待处理" },
  ],
  timeline: [
    { id: "tl-efc-01", projectId: 2, clientId: "client-efc", type: "inquiry", occurredAt: "2026-07-03", displayDate: "7 月 3 日", title: "收到金属纽扣询盘", description: "客户提供初始 Logo 与表面处理方向。", icon: "✉" },
    { id: "tl-efc-02", projectId: 2, clientId: "client-efc", type: "sample", relatedEntityId: "SP-EFC-2411-V1", occurredAt: "2026-07-08", displayDate: "7 月 8 日", title: "创建 Sample V1", description: "完成首版古铜色样品。", icon: "◈" },
    { id: "tl-efc-03", projectId: 2, clientId: "client-efc", type: "sample", relatedEntityId: "SP-EFC-2411-V2", occurredAt: "2026-07-14", displayDate: "7 月 14 日", title: "创建 Sample V2", description: "调整 Logo 深度和表面颜色。", icon: "◈" },
    { id: "tl-efc-04", projectId: 2, clientId: "client-efc", type: "communication", relatedEntityId: "fb-efc-v2-01", occurredAt: "2026-07-18", displayDate: "7 月 18 日", title: "样品获得确认", description: "客户确认 V2，可进入报价。", icon: "✓" },
    { id: "tl-efc-05", projectId: 2, clientId: "client-efc", type: "quotation", relatedEntityId: "QT-EFC-2411-V1", occurredAt: "2026-07-22", displayDate: "7 月 22 日", title: "发送并接受报价", description: "80,000 套报价获客户接受。", icon: "¥" },
    { id: "tl-efc-06", projectId: 2, clientId: "client-efc", type: "po", relatedEntityId: "po-efc-2411", occurredAt: "2026-08-02", displayDate: "8 月 2 日", title: "收到 Purchase Order", description: "收到正式 PO-EFC-240802。", icon: "▤" },
    { id: "tl-efc-07", projectId: 2, clientId: "client-efc", type: "contract", relatedEntityId: "ct-efc-240805", occurredAt: "2026-08-05", displayDate: "8 月 5 日", title: "合同确认", description: "合同已确认并转入生产排期。", icon: "✓" },
    { id: "tl-efc-08", projectId: 2, clientId: "client-efc", type: "delivery", relatedEntityId: "dl-efc-241115", occurredAt: "2026-08-05", displayDate: "计划 11 月 15 日", title: "建立计划交付", description: "计划完成 80,000 套交付。", icon: "↗" },
  ],
  weeklyReports: [],
  aiInsights: [
    { id: "ai-efc-order", projectId: 2, relatedEntityType: "po", relatedEntityId: "po-efc-2411", title: "订单摘要", content: "PO 与合同已确认，当前重点为生产排期和外箱唛头。", generatedAt: "2026-08-05", mode: "mock" },
  ],
};

const caseC: BusinessCase = {
  client: {
    id: "client-eyw",
    code: "EYW",
    name: "Emerging Yoga Wear Brand",
    country: "澳大利亚",
    region: "墨尔本",
    type: "新兴瑜伽服品牌",
    status: "培育中",
    currency: "USD",
    paymentTerm: "待商务确认",
    communicationLanguage: "English",
    primaryContactId: "contact-eyw-mia",
    lastContactAt: "2026-07-29T07:10:00Z",
    preferences: ["低饱和度颜色", "轻量辅料", "环保材料", "按系列集中评审"],
  },
  contacts: [
    { id: "contact-eyw-mia", clientId: "client-eyw", name: "Mia Collins", title: "Founder", email: "mia.collins@example-client.com", isPrimary: true, department: "Management", decisionRole: "Decision Maker", influenceLevel: "High", relationshipStrength: "Developing", lastContactAt: "2026-07-29T07:10:00Z" },
    { id: "contact-eyw-noah", clientId: "client-eyw", name: "Noah Kim", title: "Material Developer", email: "noah.kim@example-client.com", isPrimary: false, department: "Material Development", decisionRole: "Technical Approver", influenceLevel: "Medium", relationshipStrength: "Developing", lastContactAt: "2026-07-26T09:25:00Z" },
  ],
  project: {
    id: 3,
    clientId: "client-eyw",
    code: "EYW-2502",
    name: "瑜伽服品牌——2027服装辅料系列",
    customer: "Emerging Yoga Wear Brand",
    region: "澳大利亚 · 墨尔本",
    product: "隐形拉链、绳扣、织带",
    stage: "打样中",
    lifecycleStage: "sample",
    progress: "三类辅料已进入样品开发，部分 Pantone 色号、织带克重与 Logo 工艺仍待确认",
    owner: "林薇",
    ownerActorId: "actor-sales-c",
    next: "整理三类样品评审表并跟进待确认色号",
    updated: "7 月 29 日 15:12",
    lastUpdatedAt: "2026-07-29T15:12:00+08:00",
    quantity: "首单约 45,000 件套",
    delivery: "2027 年 1 月 10 日",
    health: "关注",
    contact: "Mia Collins · Founder",
    email: "mia.collins@example-client.com",
    initials: "YW",
    color: "#48645b",
    currentSummary: "隐形拉链、绳扣和织带正并行开发样品；色彩与部分结构信息不完整，尚不具备正式报价条件。",
    confirmedInformation: ["三个产品类别", "轻量哑光方向", "首单约 45,000 件套", "目标交期 2027-01-10"],
    pendingInformation: ["三组 Pantone 色号", "织带克重", "绳扣 Logo 工艺", "各产品数量拆分"],
    risks: ["颜色未确认可能触发多轮打样", "多产品数量结构缺失，无法形成正式报价"],
    nextActions: ["发送颜色确认表", "完成三类样品评审", "索取产品数量拆分"],
  },
  requirements: [
    { id: "req-eyw-01", projectId: 3, product: "隐形拉链", field: "产品类型", fieldEn: "Product Type", value: "#3 隐形拉链", status: "已确认", source: "客户询盘", updatedAt: "2026-07-20" },
    { id: "req-eyw-02", projectId: 3, product: "隐形拉链", field: "颜色", fieldEn: "Color", value: "Sand / Sage，Pantone 待确认", status: "待确认", source: "客户询盘", updatedAt: "2026-07-20" },
    { id: "req-eyw-03", projectId: 3, product: "隐形拉链", field: "长度", fieldEn: "Length", value: "20 cm / 25 cm", status: "已确认", source: "客户确认", updatedAt: "2026-07-22" },
    { id: "req-eyw-04", projectId: 3, product: "绳扣", field: "材质", fieldEn: "Material", value: "再生尼龙", status: "已确认", source: "客户确认", updatedAt: "2026-07-22" },
    { id: "req-eyw-05", projectId: 3, product: "绳扣", field: "定制 Logo", fieldEn: "Customized Logo", value: "工艺待确认", status: "未提供", source: "客户询盘", updatedAt: "2026-07-20" },
    { id: "req-eyw-06", projectId: 3, product: "绳扣", field: "颜色", fieldEn: "Color", value: "Clay，Pantone 待确认", status: "待确认", source: "客户询盘", updatedAt: "2026-07-20" },
    { id: "req-eyw-07", projectId: 3, product: "织带", field: "宽度", fieldEn: "Width", value: "20 mm", status: "已确认", source: "客户确认", updatedAt: "2026-07-22" },
    { id: "req-eyw-08", projectId: 3, product: "织带", field: "克重", fieldEn: "Weight", value: "待客户确认", status: "待确认", source: "客户询盘", updatedAt: "2026-07-20" },
    { id: "req-eyw-09", projectId: 3, product: "全系列", field: "预计数量", fieldEn: "Estimated Quantity", value: "首单约 45,000 件套；产品拆分待确认", status: "有冲突", source: "客户询盘", updatedAt: "2026-07-20" },
    { id: "req-eyw-10", projectId: 3, product: "全系列", field: "目标交期", fieldEn: "Target Delivery Date", value: "2027-01-10", status: "已确认", source: "客户确认", updatedAt: "2026-07-22" },
  ],
  samples: [
    { id: "SP-EYW-2502-ZIP", clientId: "client-eyw", projectId: 3, product: "隐形拉链", currentVersionId: "SP-EYW-2502-ZIP-V2", currentVersion: "V2", status: "制作中", createdAt: "2026-07-23", feedbackStatus: "V1 已反馈", nextAction: "按客户意见调整带色并制作 V2", specs: { size: "#3", length: "20 / 25 cm", color: "Sand / Sage", slider: "Auto-lock" } },
    { id: "SP-EYW-2502-LOCK", clientId: "client-eyw", projectId: 3, product: "再生尼龙绳扣", currentVersionId: "SP-EYW-2502-LOCK-V1", currentVersion: "V1", status: "客户评估中", createdAt: "2026-07-24", sentDate: "2026-07-27", feedbackStatus: "等待客户评估", nextAction: "确认 Logo 工艺与 Clay 色号", specs: { material: "Recycled nylon", color: "Clay", logo: "Pending", structure: "Single-hole" } },
    { id: "SP-EYW-2502-WEB", clientId: "client-eyw", projectId: 3, product: "弹力织带", currentVersionId: "SP-EYW-2502-WEB-V1", currentVersion: "V1", status: "待制作", createdAt: "2026-07-25", feedbackStatus: "等待规格确认", nextAction: "确认织带克重后排样", specs: { width: "20 mm", color: "Sand", weight: "Pending", material: "Recycled polyester blend" } },
  ],
  sampleVersions: [
    { id: "SP-EYW-2502-ZIP-V1", sampleId: "SP-EYW-2502-ZIP", projectId: 3, version: "V1", createdAt: "2026-07-23", sentDate: "2026-07-26", status: "需修改", summary: "隐形拉链首版颜色样", changes: ["初版 Sand 与 Sage 配色"] },
    { id: "SP-EYW-2502-ZIP-V2", sampleId: "SP-EYW-2502-ZIP", projectId: 3, version: "V2", createdAt: "2026-07-29", status: "制作中", summary: "调整后的隐形拉链样", changes: ["Sand 色降低黄调", "Sage 色降低灰度"] },
    { id: "SP-EYW-2502-LOCK-V1", sampleId: "SP-EYW-2502-LOCK", projectId: 3, version: "V1", createdAt: "2026-07-24", sentDate: "2026-07-27", status: "客户评估中", summary: "再生尼龙绳扣结构样", changes: ["单孔结构", "无 Logo 工艺样"] },
    { id: "SP-EYW-2502-WEB-V1", sampleId: "SP-EYW-2502-WEB", projectId: 3, version: "V1", createdAt: "2026-07-25", status: "待制作", summary: "20 mm 弹力织带首版", changes: ["等待克重确认后制作"] },
  ],
  sampleFeedback: [
    { id: "fb-eyw-zip-v1", sampleId: "SP-EYW-2502-ZIP", sampleVersionId: "SP-EYW-2502-ZIP-V1", projectId: 3, receivedAt: "2026-07-29", author: "Mia Collins", channel: "WhatsApp", summary: "两组颜色需要微调", details: "Sand 颜色略偏黄，Sage 颜色略偏灰；结构与拉合手感可以继续沿用。", requiresRevision: true },
  ],
  quotations: [],
  quotationTiers: [],
  negotiationRecords: [],
  purchaseOrders: [],
  orderLines: [],
  contracts: [],
  deliveries: [],
  shipments: [],
  communications: [
    { id: "com-eyw-01", projectId: 3, clientId: "client-eyw", type: "客户邮件", occurredAt: "2026-07-20", author: "Mia Collins", subject: "2027 trim concept board", content: "客户发送 2027 系列概念板与三类辅料方向。", language: "中英对照" },
    { id: "com-eyw-02", projectId: 3, clientId: "client-eyw", relatedEntityType: "sample", relatedEntityId: "SP-EYW-2502-ZIP-V1", type: "样品反馈", occurredAt: "2026-07-29", author: "Mia Collins", subject: "Invisible zipper color feedback", content: "Sand is slightly too yellow and Sage looks a little too grey.", language: "英文" },
  ],
  tasks: [
    { id: "task-eyw-01", projectId: 3, relatedEntityType: "sample", relatedEntityId: "SP-EYW-2502-ZIP", title: "完成隐形拉链 V2 颜色调整", owner: "林薇", priority: "P1", dueDate: "2026-08-03", status: "进行中" },
    { id: "task-eyw-02", projectId: 3, relatedEntityType: "sample", relatedEntityId: "SP-EYW-2502-WEB", title: "跟进织带克重与数量拆分", owner: "林薇", priority: "P1", dueDate: "2026-08-04", status: "待处理" },
  ],
  timeline: [
    { id: "tl-eyw-01", projectId: 3, clientId: "client-eyw", type: "inquiry", occurredAt: "2026-07-20", displayDate: "7 月 20 日", title: "收到系列开发询盘", description: "客户发送隐形拉链、绳扣与织带概念板。", icon: "✉" },
    { id: "tl-eyw-02", projectId: 3, clientId: "client-eyw", type: "requirement", occurredAt: "2026-07-22", displayDate: "7 月 22 日", title: "整理多产品需求", description: "确认基础规格并标记颜色、Logo 与克重缺口。", icon: "▣" },
    { id: "tl-eyw-03", projectId: 3, clientId: "client-eyw", type: "sample", relatedEntityId: "SP-EYW-2502-ZIP-V1", occurredAt: "2026-07-23", displayDate: "7 月 23 日", title: "创建隐形拉链 Sample V1", description: "制作 Sand 与 Sage 两组颜色样。", icon: "◈" },
    { id: "tl-eyw-04", projectId: 3, clientId: "client-eyw", type: "sample", relatedEntityId: "SP-EYW-2502-LOCK-V1", occurredAt: "2026-07-24", displayDate: "7 月 24 日", title: "创建绳扣 Sample V1", description: "制作再生尼龙单孔绳扣结构样。", icon: "◈" },
    { id: "tl-eyw-05", projectId: 3, clientId: "client-eyw", type: "sample", relatedEntityId: "SP-EYW-2502-WEB-V1", occurredAt: "2026-07-25", displayDate: "7 月 25 日", title: "建立织带 Sample V1", description: "等待克重确认后进入制作。", icon: "◈" },
    { id: "tl-eyw-06", projectId: 3, clientId: "client-eyw", type: "communication", relatedEntityId: "fb-eyw-zip-v1", occurredAt: "2026-07-29", displayDate: "7 月 29 日", title: "收到隐形拉链反馈", description: "客户要求微调 Sand 与 Sage 两组颜色。", icon: "✉" },
    { id: "tl-eyw-07", projectId: 3, clientId: "client-eyw", type: "sample", relatedEntityId: "SP-EYW-2502-ZIP-V2", occurredAt: "2026-07-29", displayDate: "7 月 29 日", title: "创建隐形拉链 Sample V2", description: "按客户反馈调整颜色。", icon: "◈" },
  ],
  weeklyReports: [],
  aiInsights: [
    { id: "ai-eyw-sample", projectId: 3, relatedEntityType: "sample", relatedEntityId: "SP-EYW-2502-ZIP", title: "样品开发摘要", content: "隐形拉链 V2 正在调色，绳扣等待评估，织带被克重信息阻塞。", generatedAt: "2026-07-29", mode: "mock" },
  ],
};

export const businessCases: BusinessCase[] = withProductLibraryLinks(withOrderExecution(withQuotationDevelopment(withSampleDevelopment([caseA, caseB, caseC]))));
