"use client";

import Image from "next/image";
import { useState } from "react";
import { productValue } from "../../lib/i18n/product-values";
import type { ProductLibraryData, SpecStatus, TypedSpecValue } from "../../lib/product-library/types";
import { getCommercialProfile, getCurrentRevision, getFactoryCandidates, getProductById, getProductReadiness, getVariantsForProduct } from "../../lib/product-library/selectors";
import { createCustomerProductDTO } from "../../lib/product-library/publication";
import { useI18n } from "../providers/language-provider";
import { Badge, Button, Card } from "../ui/primitives";
import { PageHeader } from "../layout/page-header";
import { ProductCustomerPreview } from "./product-customer-preview";

type Tab = "overview" | "specifications" | "variants" | "process" | "testing" | "factory" | "commercial" | "assets" | "preview";
const tabs: Tab[] = ["overview", "specifications", "variants", "process", "testing", "factory", "commercial", "assets", "preview"];
export function ProductDetail({ data, productId, onBack, onAdd }: { data: ProductLibraryData; productId: string; onBack: () => void; onAdd: (productId: string, variantId?: string) => void }) {
  const { t, text } = useI18n();
  const product = getProductById(data, productId);
  const variants = getVariantsForProduct(data, productId);
  const [variantId, setVariantId] = useState(variants[0]?.id ?? "");
  const [tab, setTab] = useState<Tab>("overview");
  if (!product) return <Card>{t("product.noResults")}</Card>;
  const selected = variants.find((item) => item.id === variantId) ?? variants[0];
  const revision = selected && getCurrentRevision(data, selected.id);
  const config = revision?.configuration;
  const category = data.categories.find((item) => item.id === product.categoryId);
  const sales = data.salesProfiles.find((item) => item.productId === productId);
  const commercial = getCommercialProfile(data, productId, selected?.id);
  const readiness = getProductReadiness(data, productId);
  const publication = selected && createCustomerProductDTO(data, productId, selected.id);
  const assets = data.assets.filter((item) => item.productId === productId);
  const hero = assets.find((item) => item.id === product.heroAssetId && item.kind === "image");
  const processes = data.productProcesses.filter((item) => item.revisionId === revision?.id).sort((a, b) => a.sequence - b.sequence);
  const testRequirements = data.testRequirements.filter((item) => item.revisionId === revision?.id);
  const capabilities = getFactoryCandidates(data, productId, selected?.id);
  const empty = t("product.noValue");
  const display = (value?: string) => value ? text(productValue(value)) : empty;
  const valueText = (value?: TypedSpecValue) => !value ? empty : value.kind === "text" ? text(value.value) : value.kind === "number" ? `${value.value}${value.unitCode ? ` ${value.unitCode}` : ""}` : value.kind === "boolean" ? (value.value ? t("product.confirmed") : t("product.notApplicable")) : value.optionCodes.map((code) => text(productValue(code))).join(", ");
  const statusText = (status: SpecStatus) => t(`product.${status === "not_applicable" ? "notApplicable" : status}`);
  const commonRows: Array<[string, string | number | undefined, string?]> = [
    ["material", config?.material], ["size", config?.size], ["width", config?.width, "mm"], ["length", config?.length, "cm"], ["color", config?.color], ["pantone", config?.pantone], ["finish", config?.finish], ["surface", config?.surfaceTreatment], ["logoMethod", config?.logoMethod],
  ];
  const relevantRows = commonRows.filter(([key, value]) => value !== undefined || ["material", "size", "color"].includes(key) || (key === "length" && product.categoryId === "zipper") || (key === "width" && ["tape", "label"].includes(product.categoryId)));
  const range = (value?: { min: number; max: number; unit: string }) => value ? value.unit === "days" ? t("product.days", { min: value.min, max: value.max }) : `${value.min.toLocaleString("en-US")}–${value.max.toLocaleString("en-US")} ${value.unit}` : empty;
  return <div className="product-library product-detail">
    <button className="back-link" onClick={onBack}>‹ {t("product.back")}</button>
    <PageHeader title={text(product.name)} subtitle={`${product.productCode} · ${category ? text(category.name) : product.categoryId}`} actions={<Button onClick={() => onAdd(product.id, selected?.id)}>{t("product.addToProject")}</Button>} />
    <div className="product-detail-hero"><div className="product-hero-image">{hero && <Image src={hero.fileRef} alt={text(hero.description)} width={640} height={400} />}</div><div className="product-hero-copy"><span className="eyebrow">{t("product.demo")}</span><p>{text(product.description)}</p><div className="product-hero-facts"><span>{variants.length === 1 ? t("product.variantsOne") : t("product.variants", { count: variants.length })}</span><span>{publication ? t("product.published") : t("product.internal")}</span><span>{t("product.approvedVariants", { count: readiness.approved, total: readiness.variants })}</span></div><label>{t("product.selectVariant")}<select value={selected?.id ?? ""} onChange={(event) => setVariantId(event.target.value)}>{variants.map((item) => <option value={item.id} key={item.id}>{item.variantCode}</option>)}</select></label></div></div>
    <div className="product-detail-tabs" role="tablist" aria-label={t("product.title")}>{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{t(`product.tabs.${item}`)}</button>)}</div>
    {tab === "overview" && <div className="product-detail-grid"><Card className="product-panel"><h2>{t("product.description")}</h2><p>{text(product.description)}</p><dl className="product-facts"><div><dt>{t("product.code")}</dt><dd>{product.productCode}</dd></div><div><dt>{t("common.category")}</dt><dd>{category ? text(category.name) : empty}</dd></div><div><dt>{t("product.currentRevision")}</dt><dd>{revision ? `V${revision.revisionNumber} · ${t(`product.revision.${revision.status}`)}` : empty}</dd></div><div><dt>{t("product.status")}</dt><dd>{publication ? t("product.published") : t("product.internal")}</dd></div></dl></Card><Card className="product-panel"><h2>{t("product.sellingPoints")}</h2>{sales?.sellingPoints.map((point) => <div className="product-selling-point" key={point.featureCode}><strong>{text(point.explanation)}</strong><small>{point.evidenceStatus === "documented" ? t("product.evidenceDocumented") : t("product.evidencePending")}</small></div>)}<h3>{t("product.applications")}</h3>{sales?.applications.map((item, index) => <p key={index}>{text(item)}</p>)}<h3>{t("product.readiness")}</h3><p>{t("product.approvedVariants", { count: readiness.approved, total: readiness.variants })}</p></Card></div>}
    {tab === "specifications" && <Card className="product-panel"><div className="product-panel-heading"><h2>{t("product.tabs.specifications")}</h2><span>{selected?.variantCode} · {revision ? `V${revision.revisionNumber}` : empty}</span></div>{!revision ? <p>{t("product.specsFamily")}</p> : <div className="product-spec-table"><div className="product-spec-row product-spec-head"><span>{t("common.field")}</span><span>{t("common.value")}</span><span>{t("common.status")}</span></div>{relevantRows.map(([key, value, unit]) => <div className="product-spec-row" key={key}><strong>{t(`product.${key}` as "product.material")}</strong><span>{value === undefined ? empty : unit ? `${value} ${unit}` : display(String(value))}</span><span className={value === undefined ? "is-pending" : "is-confirmed"}>{value === undefined ? t("product.pending") : t("product.confirmed")}</span></div>)}{config?.extraSpecifications.map((entry) => { const definition = data.specificationDefinitions.find((item) => item.id === entry.definitionId); return <div className="product-spec-row" key={entry.definitionId}><strong>{definition ? text(definition.label) : entry.definitionId}</strong><span>{entry.status === "confirmed" ? valueText(entry.value) : entry.status === "not_applicable" ? t("product.notApplicable") : empty}</span><span className={entry.status === "confirmed" ? "is-confirmed" : "is-pending"}>{statusText(entry.status)}</span></div>; })}</div>}</Card>}
    {tab === "variants" && <div className="product-variant-grid">{variants.map((item) => { const current = getCurrentRevision(data, item.id); return <button className={`product-variant-card card${selected?.id === item.id ? " selected" : ""}`} key={item.id} onClick={() => { setVariantId(item.id); setTab("specifications"); }}><span>{t("product.variantCode")}</span><strong>{item.variantCode}</strong><p>{current?.configuration.material ? display(current.configuration.material) : empty} · {current?.configuration.color ? display(current.configuration.color) : empty}</p><small>V{current?.revisionNumber ?? "—"} · {current ? t(`product.revision.${current.status}`) : t("product.pending")}</small></button>; })}</div>}
    {tab === "process" && <Card className="product-panel"><div className="product-panel-heading"><h2>{t("product.processSequence")}</h2><span>{selected?.variantCode}</span></div>{processes.length ? <div className="product-process-flow">{processes.map((item, index) => { const process = data.processes.find((definition) => definition.id === item.processId); return <div className="product-process-step" key={item.id}><i>{String(index + 1).padStart(2, "0")}</i><strong>{process ? text(process.name) : item.processId}</strong><small>{text(item.customerSummary)}</small>{item.customizable && <span>{t("product.customizable")}</span>}</div>; })}</div> : <p>{t("product.noProcesses")}</p>}</Card>}
    {tab === "testing" && <Card className="product-panel"><h2>{t("product.tabs.testing")}</h2>{testRequirements.length ? <div className="product-list-rows">{testRequirements.map((item) => { const test = data.tests.find((entry) => entry.id === item.testId); const capable = data.factoryTestCapabilities.filter((entry) => entry.testId === item.testId); return <div key={item.id}><strong>{test ? text(test.name) : item.testId}</strong><p>{t("product.threshold")}: {text(item.threshold)}</p><small>{t("product.testingDefinition")}: {statusText(item.status)} · {t("product.source")}: {text(item.source)}</small><small>{t("product.testCapability")}: {capable.length ? capable.map((entry) => `${data.factories.find((factory) => factory.id === entry.factoryId)?.code ?? entry.factoryId} (${t(`product.${entry.status}`)})`).join(" · ") : empty}</small></div>; })}</div> : <p>{t("product.noTests")}</p>}</Card>}
    {tab === "factory" && <Card className="product-panel"><div className="product-panel-heading"><h2>{t("product.factoryCandidate")}</h2><span>{t("product.demo")}</span></div><p className="product-muted">{t("product.factoryWarning")}</p>{capabilities.length ? <div className="product-factory-grid">{capabilities.map((item) => { const factory = data.factories.find((entry) => entry.id === item.factoryId); return <div className="product-factory-card" key={item.id}><div><strong>{factory ? text(factory.name) : item.factoryId}</strong><Badge tone={item.status === "supported" ? "green" : item.status === "unsupported" ? "red" : "amber"}>{t(`product.${item.status}`)}</Badge></div><small>{factory ? text(factory.region) : ""}</small><p>{t("product.limitations")}: {text(item.limitations)}</p><p>{t("product.moqRange")}: {range(item.moqRange)}</p><p>{t("product.sampleLead")}: {range(item.sampleLeadDays)}</p><p>{t("product.productionLead")}: {range(item.productionLeadDays)}</p><p>{t("product.processSequence")}: {item.processIds.map((id) => data.processes.find((process) => process.id === id)?.name).filter(Boolean).map((name) => text(name!)).join(" → ") || empty}</p></div>; })}</div> : <p>{t("product.noFactory")}</p>}{data.certificationScopes.filter((item) => item.targetId === config?.material || item.targetId === productId || item.targetId === selected?.id).map((item) => { const cert = data.certifications.find((entry) => entry.id === item.certificationId); return <p className="product-cert-note" key={item.id}>{t("product.certScope")}: {cert ? text(cert.name) : empty} · {text(item.note)} · {t("product.certWarning")}</p>; })}</Card>}
    {tab === "commercial" && <Card className="product-panel"><div className="product-panel-heading"><h2>{t("product.tabs.commercial")}</h2><span>{commercial.source === "variant" ? t("product.variantGuidance") : commercial.source === "product" ? t("product.familyGuidance") : t("product.pending")}</span></div><p className="product-guidance-note">{t("product.guidanceOnly")}</p><dl className="product-facts"><div><dt>{t("product.moqGuidance")}</dt><dd>{commercial.profile?.moqGuidance?.toLocaleString("en-US") ?? empty}</dd></div><div><dt>{t("product.sampleLead")}</dt><dd>{range(commercial.profile?.sampleLeadDays)}</dd></div><div><dt>{t("product.productionLead")}</dt><dd>{range(commercial.profile?.productionLeadDays)}</dd></div><div><dt>{t("product.guidance")}</dt><dd>{commercial.profile?.referencePrice === undefined ? empty : `${commercial.profile.currency} ${commercial.profile.referencePrice.toFixed(2)} · ${t("product.guidanceOnly")}`}</dd></div><div><dt>{t("product.lastUpdated")}</dt><dd>{commercial.profile?.updatedAt ?? empty}</dd></div><div><dt>{t("product.guidanceSource")}</dt><dd>{commercial.profile ? text(commercial.profile.source) : empty}</dd></div></dl><h3>{t("product.quantityGuidance")}</h3>{commercial.profile?.referenceTiers.length ? commercial.profile.referenceTiers.map((tier) => <p key={tier.minQuantity}>{tier.minQuantity.toLocaleString("en-US")}+ {tier.unit} · {commercial.profile?.currency} {tier.unitPrice.toFixed(2)}</p>) : <p>{t("product.noGuidance")}</p>}<h3>{t("product.salesNotes")}</h3><p>{sales ? text(sales.internalSalesNote) : empty}</p></Card>}
    {tab === "assets" && <Card className="product-panel"><h2>{t("product.tabs.assets")}</h2><p className="product-muted">{t("product.assetInfo")}</p><div className="product-assets-grid">{assets.map((item) => <div className="product-asset-card" key={item.id}>{item.kind === "image" && <Image src={item.fileRef} alt={text(item.description)} width={640} height={400} />}<div><strong>{text(item.description)}</strong><small>{t("product.assetKind")}: {item.kind === "image" ? t("product.assetImage") : item.kind === "technical_drawing" ? t("product.assetDrawing") : t("product.assetOther")}</small><small>{t("product.assetVersion")}: {item.assetVersion}</small></div></div>)}</div></Card>}
    {tab === "preview" && <ProductCustomerPreview product={publication} />}
    <p className="product-demo-footnote">{t("product.demo")}</p>
  </div>;
}
